import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "../components/BootstrapClient";
import StoreProvider from "../redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jaffna Vehicle Spot (PVT) LTD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
          <BootstrapClient />
        </StoreProvider>
      </body>
    </html>
  );
}
